/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package josm_missingtools;

public class App {

    public static void main(String[] args) {
        System.out.println("start");
    }
}
